version: '3.8'

services:

  app:
    image: spring-opa-app:0.0.1
    ports:
      - 8080:8080
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/rules/main

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    volumes:
      - ./opa-conf.yaml:/opa-conf.yaml
    command:
      - "run"
      - "--server"
      - "--config-file=/opa-conf.yaml"
