version: '3.8'

services:

  app:
    build: ./demo-restful-api
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/policy/com.styra.envoy.app/main/main

  envoy:
    image: envoyproxy/envoy:v1.17.0
    command:
      - "envoy"
      - "--config-path"
      - "/config/envoy.yaml"
    ports:
      - "8000:8000"
    volumes:
      - ./envoy.yaml:/config/envoy.yaml

  opa:
    image: openpolicyagent/opa:0.26.0-envoy-1
    command:
      - "run"
      - "--server"
      - "--config-file=/config/opa-conf.yaml"
    volumes:
      - ./opa-conf.yaml:/config/opa-conf.yaml
