version: '3.8'

services:

  app:
    image: openpolicyagent/demo-test-server:v1

  kong-migrations:
    image: kong-opa:2.0
    command: ["kong", "migrations", "bootstrap"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    restart: on-failure

  kong:
    image: kong-opa:2.0
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: postgres
      KONG_LOG_LEVEL: debug
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PLUGINS: bundled,opa
    ports:
      - "8000-8001:8000-8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    restart: on-failure

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong

  opa:
    image: openpolicyagent/opa:latest
    command:
      - "run"
      - "--server"
      - "--config-file=/config/opa-conf.yaml"
    volumes:
      - ./opa-conf.yaml:/config/opa-conf.yaml
    ports:
      - "8181:8181"
