version: '3.8'

services:

  app:
    image: openpolicyagent/demo-test-server:v1

  kong:
    image: kong-opa:2.6.0
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      KONG_PLUGINS: bundled,opa
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml

  opa:
    image: openpolicyagent/opa:latest
    command:
      - "run"
      - "--server"
      - "--config-file=/config/opa-conf.yaml"
    ports:
      - "8181:8181"
    volumes:
      - ./opa-conf.yaml:/config/opa-conf.yaml
