apiVersion: kuma.io/v1alpha1
kind: OPAPolicy
mesh: default
metadata:
  name: opa-policy-inline
spec:
  selectors:
  - match:
      kuma.io/service: '*'
  conf:
    agentConfig:
      inlineString: |
        decision_logs:
          console: true
    policies:
      - inlineString: |
          package envoy.authz

          import input.attributes.request.http as http_request

          default allow = false

          allow {
            http_request.method == "GET"
            input.parsed_path = ["get"]
          }
