kind: Secret
apiVersion: v1
metadata:
  name: opa-das-config
  namespace: istio-opa-demo
stringData:
  conf.yaml: |
    services:
    - name: styra
      url: https://<styra-organization-id>/v1
      credentials:
        bearer:
          token: <styra-token>
    labels:
      system-type: "istio"
      system-id: <styra-system-id>
    discovery:
      name: discovery
      resource: /systems/<styra-system-id>/discovery
      service: 'styra'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-app
  namespace: istio-opa-demo
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: app
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
        - name: opa
          image: openpolicyagent/opa:latest-envoy
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: opa-config
          args:
          - "run"
          - "--server"
          - "--ignore=.*"
          - "--config-file=/config/conf.yaml"
      volumes:
      - name: opa-config
        secret:
          secretName: opa-das-config
---
apiVersion: v1
kind: Service
metadata:
  name: example-app-service
  namespace: istio-opa-demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: example-app
  type: NodePort
