kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-envoy-config
  namespace: istio-opa-demo
data:
  conf.yaml: |
    services:
      - name: styra
        url: https://<styra-organization-id>/v1
        credentials:
          bearer:
            token: "<styra-token>"
    labels:
      system-id: "<styra-system-id>"
      system-type: "envoy"
    discovery:
      name: discovery
      prefix: "/systems/<styra-system-id>"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: example-app
  namespace: istio-opa-demo
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: app
          image: pvsone/demo-restful-api:0.3
          ports:
            - containerPort: 5000
          env:
          - name: POLICY_PATH
            value: /v1/data/policy/com.styra.envoy.app/main/main
        - name: opa
          image: openpolicyagent/opa:0.26.0-envoy-1
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: opa-config-vol
          args:
          - "run"
          - "--server"
          - "--ignore=.*"
          - "--config-file=/config/conf.yaml"
      volumes:
      - name: opa-config-vol
        configMap:
          name: opa-envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: example-app-service
  namespace: istio-opa-demo
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: example-app
  type: NodePort
