apiVersion: kuma.io/v1alpha1
kind: OPAPolicy
mesh: default
metadata:
  name: opa-policy-das
spec:
  selectors:
  - match:
      kuma.io/service: '*'
  conf:
    agentConfig:
      inlineString: |
        services:
        - name: styra
          url: https://<styra-organization-id>/v1
          credentials:
            bearer:
              token: "<styra-token>"
        labels:
          system-id: "<styra-system-id>"
          system-type: "kong"
        bundles:
          systems/<styra-system-id>:
            polling:
              max_delay_seconds: 15
              min_delay_seconds: 10
            resource: /bundles/systems/<styra-system-id>
            service: styra
        decision_logs:
          reporting:
            max_delay_seconds: 15
            min_delay_seconds: 10
            upload_size_limit_bytes: 131072
          service: styra
        default_decision: main/main
        status:
          service: styra
